# Generated by Django 6.0.7 on 2026-09-06 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='EMAIL',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='msg',
            new_name='MSG',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='NAME',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='PHONE',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stname',
            new_name='SNAME',
        ),
    ]
