# Generated by Django 6.0.7 on 2026-09-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_email_student_email_rename_msg_student_msg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=30)),
                ('PHONE', models.IntegerField()),
                ('EMAIL', models.EmailField(max_length=254)),
                ('MSG', models.CharField(max_length=100)),
            ],
        ),
    ]
